//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagementApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeManagementApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorToast {
            get {
                return ResourceManager.GetString("ErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to identify item for deletion.
        /// </summary>
        internal static string ErrorToastDelete {
            get {
                return ResourceManager.GetString("ErrorToastDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebase error.
        /// </summary>
        internal static string ErrorToastFirebase {
            get {
                return ResourceManager.GetString("ErrorToastFirebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebase auth error.
        /// </summary>
        internal static string ErrorToastFirebaseAuth {
            get {
                return ResourceManager.GetString("ErrorToastFirebaseAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded data successfully.
        /// </summary>
        internal static string LoadedDataToast {
            get {
                return ResourceManager.GetString("LoadedDataToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create task.
        /// </summary>
        internal static string PersonalTaskButton {
            get {
                return ResourceManager.GetString("PersonalTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new task.
        /// </summary>
        internal static string PersonalTaskEntry1 {
            get {
                return ResourceManager.GetString("PersonalTaskEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new personal task.
        /// </summary>
        internal static string PersonalTaskLabel1 {
            get {
                return ResourceManager.GetString("PersonalTaskLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My current personal tasks.
        /// </summary>
        internal static string PersonalTaskLabel2 {
            get {
                return ResourceManager.GetString("PersonalTaskLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal tasks.
        /// </summary>
        internal static string PersonalTaskTitle {
            get {
                return ResourceManager.GetString("PersonalTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account details:.
        /// </summary>
        internal static string SettingsLabel1 {
            get {
                return ResourceManager.GetString("SettingsLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App information.
        /// </summary>
        internal static string SettingsLabel2 {
            get {
                return ResourceManager.GetString("SettingsLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SettingsSignOut {
            get {
                return ResourceManager.GetString("SettingsSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create event.
        /// </summary>
        internal static string SharedEventButton {
            get {
                return ResourceManager.GetString("SharedEventButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event created successfully.
        /// </summary>
        internal static string SharedEventConfirmation {
            get {
                return ResourceManager.GetString("SharedEventConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Event.
        /// </summary>
        internal static string SharedEventDeletion {
            get {
                return ResourceManager.GetString("SharedEventDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the event.
        /// </summary>
        internal static string SharedEventDeletionConfirmation {
            get {
                return ResourceManager.GetString("SharedEventDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event deleted successfully.
        /// </summary>
        internal static string SharedEventDeletionToast {
            get {
                return ResourceManager.GetString("SharedEventDeletionToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new event.
        /// </summary>
        internal static string SharedEventEntry1 {
            get {
                return ResourceManager.GetString("SharedEventEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new shared event.
        /// </summary>
        internal static string SharedEventLabel1 {
            get {
                return ResourceManager.GetString("SharedEventLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current events.
        /// </summary>
        internal static string SharedEventLabel2 {
            get {
                return ResourceManager.GetString("SharedEventLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared events.
        /// </summary>
        internal static string SharedEventTitle {
            get {
                return ResourceManager.GetString("SharedEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an event and pick a date first!.
        /// </summary>
        internal static string SharedEventToastNull {
            get {
                return ResourceManager.GetString("SharedEventToastNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create task.
        /// </summary>
        internal static string SharedTaskButton {
            get {
                return ResourceManager.GetString("SharedTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new task.
        /// </summary>
        internal static string SharedTaskEntry {
            get {
                return ResourceManager.GetString("SharedTaskEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new shared task.
        /// </summary>
        internal static string SharedTaskLabel {
            get {
                return ResourceManager.GetString("SharedTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My current tasks.
        /// </summary>
        internal static string SharedTaskLabel2 {
            get {
                return ResourceManager.GetString("SharedTaskLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a target user.
        /// </summary>
        internal static string SharedTaskPicker {
            get {
                return ResourceManager.GetString("SharedTaskPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a task and pick a user first!.
        /// </summary>
        internal static string SharedTasksToastNull {
            get {
                return ResourceManager.GetString("SharedTasksToastNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared task.
        /// </summary>
        internal static string SharedTaskTitle {
            get {
                return ResourceManager.GetString("SharedTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item to shopping list.
        /// </summary>
        internal static string ShoppingListButton1 {
            get {
                return ResourceManager.GetString("ShoppingListButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shopping list.
        /// </summary>
        internal static string ShoppingListButton2 {
            get {
                return ResourceManager.GetString("ShoppingListButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this shopping list?.
        /// </summary>
        internal static string ShoppingListConfirmationDeletion {
            get {
                return ResourceManager.GetString("ShoppingListConfirmationDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create this shopping list?.
        /// </summary>
        internal static string ShoppingListCreationConfirm {
            get {
                return ResourceManager.GetString("ShoppingListCreationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list created.
        /// </summary>
        internal static string ShoppingListCreationToast {
            get {
                return ResourceManager.GetString("ShoppingListCreationToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete shopping list.
        /// </summary>
        internal static string ShoppingListDelete {
            get {
                return ResourceManager.GetString("ShoppingListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping list successfully deleted.
        /// </summary>
        internal static string ShoppingListDeletioniToast {
            get {
                return ResourceManager.GetString("ShoppingListDeletioniToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a shopping item.
        /// </summary>
        internal static string ShoppingListEntry {
            get {
                return ResourceManager.GetString("ShoppingListEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new shopping list.
        /// </summary>
        internal static string ShoppingListLabel1 {
            get {
                return ResourceManager.GetString("ShoppingListLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My current shopping lists.
        /// </summary>
        internal static string ShoppingListLabel2 {
            get {
                return ResourceManager.GetString("ShoppingListLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping lists.
        /// </summary>
        internal static string ShoppingListTitle {
            get {
                return ResourceManager.GetString("ShoppingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an item first!.
        /// </summary>
        internal static string ShoppingListToastNull {
            get {
                return ResourceManager.GetString("ShoppingListToastNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a user and add shopping items first!.
        /// </summary>
        internal static string ShoppingListToastNull2 {
            get {
                return ResourceManager.GetString("ShoppingListToastNull2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInButton1 {
            get {
                return ResourceManager.GetString("SignInButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignInButton2 {
            get {
                return ResourceManager.GetString("SignInButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail.
        /// </summary>
        internal static string SignInEntry1 {
            get {
                return ResourceManager.GetString("SignInEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Password.
        /// </summary>
        internal static string SignInEntry2 {
            get {
                return ResourceManager.GetString("SignInEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to proceed!.
        /// </summary>
        internal static string SignInLabel1 {
            get {
                return ResourceManager.GetString("SignInLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string SignInLabel2 {
            get {
                return ResourceManager.GetString("SignInLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string SignInLabel3 {
            get {
                return ResourceManager.GetString("SignInLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string SignInLabel4 {
            get {
                return ResourceManager.GetString("SignInLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in successfully.
        /// </summary>
        internal static string SignInToast1 {
            get {
                return ResourceManager.GetString("SignInToast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to sign out?.
        /// </summary>
        internal static string SignOutConfirmation {
            get {
                return ResourceManager.GetString("SignOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User signed out successfully.
        /// </summary>
        internal static string SignOutSuccess {
            get {
                return ResourceManager.GetString("SignOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string SignUpEntry1 {
            get {
                return ResourceManager.GetString("SignUpEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail.
        /// </summary>
        internal static string SignUpEntry2 {
            get {
                return ResourceManager.GetString("SignUpEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        internal static string SignUpEntry3 {
            get {
                return ResourceManager.GetString("SignUpEntry3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the password.
        /// </summary>
        internal static string SignUpEntry4 {
            get {
                return ResourceManager.GetString("SignUpEntry4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string SignUpLabel1 {
            get {
                return ResourceManager.GetString("SignUpLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string SignUpLabel2 {
            get {
                return ResourceManager.GetString("SignUpLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string SignUpLabel3 {
            get {
                return ResourceManager.GetString("SignUpLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string SignUpLabel4 {
            get {
                return ResourceManager.GetString("SignUpLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password:.
        /// </summary>
        internal static string SignUpLabel5 {
            get {
                return ResourceManager.GetString("SignUpLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username first!.
        /// </summary>
        internal static string SignUpToastNullUsername {
            get {
                return ResourceManager.GetString("SignUpToastNullUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        internal static string SignUpToastPasswordsMissmatch {
            get {
                return ResourceManager.GetString("SignUpToastPasswordsMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed up successfully.
        /// </summary>
        internal static string SignUpToastSuccess {
            get {
                return ResourceManager.GetString("SignUpToastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the task .
        /// </summary>
        internal static string TaskDeletionConfirmation {
            get {
                return ResourceManager.GetString("TaskDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully created.
        /// </summary>
        internal static string TaskToast {
            get {
                return ResourceManager.GetString("TaskToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully deleted.
        /// </summary>
        internal static string TaskToastDelete {
            get {
                return ResourceManager.GetString("TaskToastDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        internal static string TaskToastDeletion {
            get {
                return ResourceManager.GetString("TaskToastDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a task first!.
        /// </summary>
        internal static string TaskToastNull {
            get {
                return ResourceManager.GetString("TaskToastNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
